# Generated by Django 5.2.6 on 2025-09-23 05:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('contact_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^07\\d{8}$', 'Enter a valid phone number e.g., 07XXXXXXXX')])),
                ('test_type', models.CharField(choices=[('blood-test', 'Blood Test'), ('xray', 'X-Ray'), ('mri', 'MRI Scan'), ('ct-scan', 'CT Scan'), ('covid-test', 'COVID-19 Test'), ('general-checkup', 'General Checkup')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('hospital_name', models.CharField(choices=[('kenyatta', 'Kenyatta National Hospital'), ('nairobi-hospital', 'The Nairobi Hospital'), ('aga-khan', 'Aga Khan University Hospital'), ('moi-teaching', 'Moi Teaching & Referral Hospital'), ('coast-general', 'Coast General Teaching & Referral Hospital'), ('other', 'Other')], max_length=100)),
                ('booking_ref', models.CharField(editable=False, max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('patient_name', 'test_type', 'date', 'time'), name='unique_booking_per_patient')],
            },
        ),
    ]
