# Generated by Django 5.2.6 on 2025-09-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UzimaHealth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_ref',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
